title: Richhiey Thomas Home | My little space on the internet
author: Richhiey Thomas
email: richhiey1996@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Richhiey Thomas blog | My little space on the internet
show_excerpts: true # set to true to show excerpts on the homepage

remote_theme: richhiey1996/texture


# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/

texture:
  title: Richhiey Thomas
  tagline: Software Engineer playing Music with AI
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: richhiey
    github:  richhiey1996
    linkedIn: in/richhiey
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
#theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
